    ```bash
    # Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
    # Use either `docker-compose` or individual `docker build` commands
    # Build
      - docker build -t udagram-api-feed ./udagram-api-feed
      - docker build -t udagram-api-user ./udagram-api-user
      - docker build -t udagram-frontend ./udagram-frontend
      - docker build -t reverseproxy ./udagram-reverseproxy
    # Do similar for other three images
    ```

    ```bash
    # Tagging
      - docker tag udagram-api-feed luqmanshofuleji/udagram-api-feed:v2
      - docker tag udagram-api-user luqmanshofuleji/udagram-api-user:v2
      - docker tag udagram-frontend:local luqmanshofuleji/udagram-frontend:v2
      - docker tag reverseproxy luqmanshofuleji/reverseproxy:v2
    # Do similar for other three images```
    ```bash
    # Push
    # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push luqmanshofuleji/udagram-api-feed:v2
      - docker push luqmanshofuleji/udagram-api-user:v2
      - docker push luqmanshofuleji/udagram-frontend:v2
      - docker push luqmanshofuleji/reverseproxy:v2
    # Do similar for other three images
    ```